### ISSUE TITLE
IronPython 

### ISSUE THREAD

**Issue by hjakobwagner** [compas-Workshops/WS_cluster#1]
i have both rhino 5 and 6 installed 

when trying to run the verify_rhino.py file in rhino 5 (after running
python -m compas_rhino.install -v 5.0 -p compas compas_rhino compas_ghpython

and getting all OKs ...

i get the error "No Module named Compas" (line1) when i want to run the python script in rhino 5...

for rhino 6 i get this errors: 

Installing COMPAS packages to Rhino 6.0 IronPython lib:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\workshop\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\workshop\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\workshop\lib\site-packages\compas_rhino\install.py", line 148, in <module>
    install(version=args.version, packages=args.packages)
  File "C:\ProgramData\Anaconda3\envs\workshop\lib\site-packages\compas_rhino\install.py", line 77, in install
    ipylib_path = compas_rhino._get_ironpython_lib_path(version)
  File "C:\ProgramData\Anaconda3\envs\workshop\lib\site-packages\compas_rhino\__init__.py", line 48, in _get_ironpython_lib_path
    raise Exception("The lib folder for IronPython does not exist in this location: {}".format(ironpython_lib_path))
Exception: The lib folder for IronPython does not exist in this location: C:\Users\localadmin\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib

This folder would actually exist: (local user ...) 
C:\Users\ac128044\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib

but can't figure out how to direct to the right location ...

**Comment by gonzalocasas** [comment]
> i get the error "No Module named Compas" (line1) when i want to run the python script in rhino 5...

Does it literally say `Compas` capitalized? If so, there's a typo somewhere. If -however- it says it cannot find `compas` all lowercase, then the installation didn't work out properly. 

Judging by the next error on Rhino 6, it looks like your local user does not have admin rights and Windows is switching users when you use `Run as administrator`. To workaround the issue, start the Anaconda Prompt as admin, then set the value of the `APPDATA` variable to point to your local user instead of the `localadmin` one, and try again (to set the variable, type `set APPDATA=C:\Users\ac128044\AppData\Roaming` on the Anaconda Prompt`, this setting is temporary and will go away when you close the prompt, but it might be enough for the installation to work properly).

**Comment by hjakobwagner** [comment]
Thanks the hack with the appdata path worked for Rhino 6!

**Comment by vvv29** [comment]
Hello, I am having a similar error, I have Rhino 7 installed. 
And have tried the suggestion above. 
But with no good results 
Below is the traceback

  File "C:\Users\0000\anaconda3\envs\research\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\0000\anaconda3\envs\research\lib\site-packages\compas_rhino\install.py", line 275, in <module>
    install(version=args.version, packages=args.packages)
  File "C:\Users\0000\anaconda3\envs\research\lib\site-packages\compas_rhino\install.py", line 52, in install
    ipylib_path = compas_rhino._get_ironpython_lib_path(version)
  File "C:\Users\0000\anaconda3\envs\research\lib\site-packages\compas_rhino\__init__.py", line 75, in _get_ironpython_lib_path
    raise Exception("The lib folder for IronPython does not exist in this location: {}".format(ironpython_lib_path))
Exception: The lib folder for IronPython does not exist in this location: C:\Users\0000\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib
